services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: admin

  mongo-init:
    image: mongo
    depends_on:
      - mongo
    entrypoint: >
      bash -c '
      echo "Creating application user and test database user...";
      mongo --host mongo -u root -p pass --authenticationDatabase admin <<EOF;
      use test;
      db.createUser({ user: "testUser", pwd: "testPass", roles: [{ role: "readWrite", db: "test" }] });
      EOF
      '

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false